development:
  sessions:
    default:
      database: cricdata_development
      hosts:
        - db.cricdata.org:27017
      options:
        consistency: :strong
test:
  sessions:
    default:
      database: cricdata_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
production:
  sessions:
    default:
      database: "<%= ENV['MONGOID_DATABASE'] %>"
      hosts:
        - "<%= ENV['MONGOID_HOST'] %>:<%= ENV['MONGOID_PORT'] %>"
      options:
        consistency: :strong

