development:
  clients:
    default:
      database: cricdata_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: cricdata_test
      hosts:
        - localhost:27017
production:
  clients:
    default:
      database: "<%= ENV['MONGOID_DATABASE'] %>"
      hosts:
        - "<%= ENV['MONGOID_HOST'] %>:<%= ENV['MONGOID_PORT'] %>"
